#!/usr/bin/env ruby

require './lib/quiz.rb'
require 'getopt/long'

def usage
  STDERR.puts <<eos
Usage: #{$0} filename.rb renderer [options]
filename.rb contains questions expressed in the quiz DSL

renderer choices are:
  xml    - Coursera HTML format for online auto-grading
  html5  - HTML 5 suitable for Web display/printing

The HTML5 renderer supports these options:
  -c <href>, --css=<href>
      embed <href> for stylesheet into generated HTML5
  -t <file.html.erb>, --template=<file.html.erb>
      Use file.html.erb as HTML template rather than generating our own file.
      file.html.erb should have <%= yield %> where questions should go.
      In the template, local variable 'title' holds the quiz title.
  -s, --solutions
      generate solutions (showing correct answers and explanations)

eos
  exit
end

def main
  filename = ARGV.shift
  raise "Cannot read #{filename}" unless File.readable? filename
  renderer = ARGV.shift
  raise "Unknown renderer '#{renderer}'" unless Quiz.get_renderer(renderer)
  opts = Getopt::Long.getopts(
    ['-c', '--css', Getopt::REQUIRED],
    ['-t', '--template', Getopt::REQUIRED],
    ['-s', '--solutions', Getopt::BOOLEAN],
    )
  quiz = Quiz.instance_eval "#{IO.read(filename)}"
  puts quiz.render_with(renderer, opts)
end

usage if ARGV.length < 2
main

